export const COLLECTIONS = {
  USERS: 'users',
  ORDERS: 'orders',
  LOGS: 'logs',
  SYSTEM_LOCKS: 'systemLocks'
};

export const SYSTEM_LOCK_IDS = {
  ORDER_IMPORT: 'order-import'
};

export const ORDER_SOURCE = {
  MANUAL: 'manual',
  EXCEL_PASTE: 'excel_paste'
};

export const LOG_ACTIONS = {
  CREATE_ORDER: 'CREATE_ORDER',
  UPDATE_ORDER: 'UPDATE_ORDER',
  UPDATE_PRODUCT_ITEM: 'UPDATE_PRODUCT_ITEM',
  PRINT_ORDER: 'PRINT_ORDER',
  REPRINT_ORDER: 'REPRINT_ORDER',
  COMPLETE_ORDER: 'COMPLETE_ORDER',
  REOPEN_ORDER: 'REOPEN_ORDER',
  CANCEL_ORDER: 'CANCEL_ORDER',
  RESTORE_ORDER: 'RESTORE_ORDER',
  IMPORT_PREVIEW: 'IMPORT_PREVIEW',
  CREATE_ORDER_FROM_IMPORT: 'CREATE_ORDER_FROM_IMPORT',
  IMPORT_VALIDATION_FAILED: 'IMPORT_VALIDATION_FAILED'
};

export const DEFAULT_ORDER_QUERY_LIMIT = 100;
export const DASHBOARD_ORDER_QUERY_LIMIT = 5000;
export const DASHBOARD_RECENT_MONTHS = 3;
export const IMPORT_LOCK_TIMEOUT_MS = 10 * 60 * 1000;
