export const PERMISSIONS = {
  ORDERS_VIEW: 'orders:view',
  ORDERS_IMPORT: 'orders:import',
  ORDERS_CREATE: 'orders:create',
  ORDERS_EDIT: 'orders:edit',
  ORDERS_ITEM_UPDATE: 'orders:item-update',
  ORDERS_PRINT: 'orders:print',
  ORDERS_COMPLETE: 'orders:complete',
  ORDERS_CANCEL: 'orders:cancel',
  LOGS_VIEW: 'logs:view',
  USERS_VIEW: 'users:view',
  USERS_MANAGE: 'users:manage'
};

export const ROLE_PERMISSIONS = {
  admin: [
    PERMISSIONS.ORDERS_VIEW,
    PERMISSIONS.ORDERS_IMPORT,
    PERMISSIONS.ORDERS_CREATE,
    PERMISSIONS.ORDERS_EDIT,
    PERMISSIONS.ORDERS_ITEM_UPDATE,
    PERMISSIONS.ORDERS_PRINT,
    PERMISSIONS.ORDERS_COMPLETE,
    PERMISSIONS.ORDERS_CANCEL,
    PERMISSIONS.LOGS_VIEW,
    PERMISSIONS.USERS_VIEW,
    PERMISSIONS.USERS_MANAGE
  ],
  staff: [
    PERMISSIONS.ORDERS_VIEW,
    PERMISSIONS.ORDERS_ITEM_UPDATE,
    PERMISSIONS.ORDERS_PRINT,
    PERMISSIONS.ORDERS_COMPLETE,
    PERMISSIONS.ORDERS_CANCEL,
    PERMISSIONS.LOGS_VIEW
  ],
  viewer: [
    PERMISSIONS.ORDERS_VIEW,
    PERMISSIONS.LOGS_VIEW
  ]
};
